export const QUOTES = [
  "Save money now, thank yourself later.",
  "Small savings today build big futures.",
  "Don’t save what’s left—spend what’s left after saving.",
  "A rupee saved is a rupee earned.",
  "Savings is the first step to freedom.",
  "Your future depends on today’s savings.",
  "Save before you spend, not after.",
  "Discipline creates savings, savings create wealth.",
  "Saving is a habit, not an event.",
  "Every coin counts.",
  "Spend with purpose, not emotion.",
  "If you can’t buy it twice, don’t buy it once.",
  "Control your money, or it will control you.",
  "Needs first, wants later.",
  "Don’t let discounts fool your budget.",
  "Spending wisely is earning silently.",
  "Think twice before every purchase.",
  "Money flows where discipline goes.",
  "Avoid impulse, embrace intention.",
  "Your expenses define your future.",
  "Wealth is built slowly, not instantly.",
  "Consistency beats intensity in wealth creation.",
  "Invest in assets, not liabilities.",
  "Money grows where patience lives.",
  "Wealth is a result of habits.",
  "Build income streams, not excuses.",
  "Financial freedom is earned, not given.",
  "Make your money work for you.",
  "Wealth is a journey, not a destination.",
  "Grow your money, don’t just save it.",
  "Track every rupee you spend.",
  "What gets tracked gets controlled.",
  "Budgeting is telling money where to go.",
  "Daily discipline creates financial stability.",
  "Expenses ignored become problems.",
  "A budget is your financial GPS.",
  "Plan your spending, don’t guess it.",
  "Awareness reduces waste.",
  "Control small leaks before they sink your ship.",
  "Daily tracking leads to long-term success.",
  "Discipline today, comfort tomorrow.",
  "Financial control is self-control.",
  "Consistency beats motivation in saving.",
  "Wealth respects discipline.",
  "Financial habits define your life.",
  "Control spending, control life.",
  "Discipline is the bridge to wealth.",
  "Money follows structured behavior.",
  "Stick to the plan, no matter what.",
  "Habits shape your financial destiny.",
  "Start saving, even if it’s small.",
  "Progress is better than perfection.",
  "Your financial journey starts today.",
  "Every day is a chance to improve money habits.",
  "Build slowly, grow steadily.",
  "Financial success is daily effort.",
  "Don’t wait, start managing today.",
  "Growth begins with awareness.",
  "Small steps lead to big wealth.",
  "Start now, not later.",
  "Saving is good, investing is better.",
  "Money should grow, not sit idle.",
  "Invest for the long term.",
  "Patience builds portfolios.",
  "Risk managed is growth earned.",
  "Don’t fear investing, learn it.",
  "Compounding rewards patience.",
  "Time in market beats timing the market.",
  "Invest early, benefit later.",
  "Let your money multiply.",
  "Avoid debt, build assets.",
  "Live below your means.",
  "Simplicity leads to savings.",
  "Financial peace > flashy lifestyle.",
  "Save first, celebrate later.",
  "Wealth is quiet, debt is loud.",
  "Spend less than you earn.",
  "Budget is your best friend.",
  "Save consistently, not occasionally.",
  "Control today, secure tomorrow.",
  "Think long-term, act daily.",
  "Wealth takes time.",
  "Patience is profitable.",
  "Plan today for tomorrow.",
  "Future you is watching.",
  "Build for decades, not days.",
  "Short-term sacrifice, long-term gain.",
  "Time + discipline = wealth.",
  "Stay consistent, stay patient.",
  "Delayed gratification builds riches.",
  "Money is a tool, not a goal.",
  "Learn before you earn more.",
  "Financial literacy is power.",
  "Smart people manage money.",
  "Wealth starts in the mind.",
  "Think like an investor.",
  "Money habits define success.",
  "Educate yourself financially.",
  "Change mindset, change life.",
  "Financial clarity brings confidence.",
  "Save more. Spend less.",
  "Wealth = habits.",
  "Budget matters.",
  "Discipline wins.",
  "Grow money.",
  "Avoid waste.",
  "Think ahead.",
  "Stay consistent.",
  "Track expenses.",
  "Invest wisely.",
  "Rich life starts with small savings.",
  "Money grows where discipline flows.",
  "Expenses unmanaged destroy wealth.",
  "Your money reflects your habits.",
  "Build wealth silently.",
  "Save like your future depends on it—because it does.",
  "Don’t chase money, manage it.",
  "Wealth rewards patience.",
  "Financial control is ultimate freedom.",
  "Make every rupee count.",
  "Budget today, freedom tomorrow.",
  "Spend less, stress less.",
  "Save consistently, grow endlessly.",
  "Plan your finances, plan your life.",
  "Control spending, control destiny.",
  "Money saved is opportunity gained.",
  "Financial awareness changes everything.",
  "Avoid waste, build wealth.",
  "Smart money moves matter.",
  "Think before you spend.",
  "Save smart, live better.",
  "Wealth is built daily.",
  "Spend consciously.",
  "Track everything.",
  "Stay disciplined.",
  "Grow slowly.",
  "Invest early.",
  "Avoid debt.",
  "Be consistent.",
  "Financial freedom is a choice."
];

// Formatting personalized quotes
export const PERSONALIZED_TEMPLATES = [
  "Hello {name}, save a little today 💰",
  "{name}, your future is funded by today’s discipline.",
  "Stay consistent, {name} — wealth follows habits.",
  "Track today to relax tomorrow, {name}.",
  "Make smart money moves today, {name}."
];

export function getQuoteOfTheDay(firstName = '') {
  // Use today's date string as a seed so it changes once per day
  const todayStr = new Date().toDateString();
  let seed = 0;
  for (let i = 0; i < todayStr.length; i++) {
    seed += todayStr.charCodeAt(i);
  }

  // 10% chance to show a personalized name template if configured
  if (firstName && seed % 10 < 3) {
    const templateIndex = seed % PERSONALIZED_TEMPLATES.length;
    return PERSONALIZED_TEMPLATES[templateIndex].replace('{name}', firstName.split(' ')[0]);
  }

  // Otherwise pick a random quote
  const quoteIndex = seed % QUOTES.length;
  return QUOTES[quoteIndex];
}
